title: Following the Tutorial
author: N. N.
email: placeholderemail@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Test page.

# social links
twitter_username: No Twitter
github_username:  N.N. 2017

show_excerpts: true # set to false to remove excerpts on the homepage
